package com.rupi.api.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHENTICATED,
    FORBIDDEN,
    NOT_FOUND,
    USERNAME_TAKEN,
    IDEMPOTENCY_IN_PROGRESS,
    IDEMPOTENCY_KEY_REUSED,
    INSUFFICIENT_FUNDS,
    FAUCET_COOLDOWN,
    FAUCET_CAP_REACHED,
    RATE_LIMITED,
    INTERNAL_ERROR
}
